config/routes.rb
HelenaAdministration::Engine.routes.draw do
  get 'dashboard/index'

  root 'dashboard#index'

  resource :import_survey, only: %i[new create]
  resources :surveys do
    resources :sessions
    resources :versions do
      resources :question_groups do
        resources :questions
        resource :questions do
          resources :short_texts, module: 'questions'
          resources :long_texts, module: 'questions'
          resources :static_texts, module: 'questions'
          resources :radio_groups, module: 'questions'
          resources :checkbox_groups, module: 'questions'
          resources :radio_matrices, module: 'questions'
          resources :bipolar_radio_matrices, module: 'questions'
          resources :checkbox_matrices, module: 'questions'
        end
      end
    end
  end
end

app/models/helena_administration/import_survey_form.rb
module HelenaAdministration
  class ImportSurveyForm
    include ActiveModel::Model

    attr_accessor :script

    validates :script, presence: true
  end
end

app/controllers/helena_administration/application_controller.rb
module HelenaAdministration
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :set_locale

    def add_breadcrumb(name, path = nil, options = {})
      super(name.presence || t('shared.untitled'), path, options)
    end

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end
end

app/controllers/helena_administration/dashboard_controller.rb
module HelenaAdministration
  class DashboardController < ApplicationController
    before_action :add_breadcrumbs

    private

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
    end
  end
end

app/controllers/helena_administration/import_surveys_controller.rb
module HelenaAdministration
  class ImportSurveysController < ApplicationController
    before_action :add_breadcrumbs

    def new
      add_breadcrumb t('.import')
      @import_survey_form = ImportSurveyForm.new
    end

    # rubocop:disable Metrics/MethodLength
    def create
      @import_survey_form = ImportSurveyForm.new import_survey_form_params
      if @import_survey_form.valid?
        begin
          Helena::SurveyImporter.new @import_survey_form.script
          flash[:success] = t('shared.actions.created')
          redirect_to surveys_path
        rescue StandardError => e
          @error = e

          render 'new'
        end
      else
        flash.now[:danger] = t('shared.actions.error')
        render 'new'
      end
    end
    # rubocop:enable Metrics/MethodLength

    private

    def import_survey_form_params
      params.require(:import_survey_form).permit(:script)
    end

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
    end
  end
end

app/controllers/helena_administration/question_groups_controller.rb
module HelenaAdministration
  class QuestionGroupsController < ApplicationController
    respond_to :html

    before_action :load_version, :add_breadcrumbs
    before_action :load_question_group, only: %i[destroy edit update show]

    def show
      add_breadcrumb @question_group.title
    end

    def new
      @question_group = @version.question_groups.build
      add_breadcrumb t('.new')
    end

    def create
      @question_group = @version.question_groups.build question_group_params
      # Note: Not used at the moment, because there are no validations atm
      # if @question_group.save
      #   flash[:success] = t 'shared.actions.created'
      # else
      #   flash.now[:danger] = t 'shared.actions.error'
      # end
      flash[:success] = t 'shared.actions.created' if @question_group.save
      respond_with @question_group, location: [@survey, @version, @question_group]
    end

    def edit
      add_breadcrumb @question_group.title
    end

    def update
      flash[:success] = t('shared.actions.updated') if @question_group.update_attributes(question_group_params)

      # Note: Not used at the moment, because there are no validations atm
      # if @question_group.update_attributes(question_group_params)
      #   flash[:success] = t 'shared.actions.updated'
      # else
      #   flash.now[:danger] = t 'shared.actions.error'
      #   add_breadcrumb @question_group.title_was
      # end

      respond_with @question_group, location: [@survey, @version, @question_group]
    end

    def destroy
      flash[:success] = t 'shared.actions.deleted' if @question_group.destroy
      respond_with @question_group, location: [@survey, @version]
    end

    private

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
      add_breadcrumb Helena::Survey.model_name.human(count: 2), surveys_path
      add_breadcrumb @survey.name, @survey
      add_breadcrumb t('helena_administration.versions.version', version: @version.version), [@survey, @version]
    end

    def load_version
      @survey = Helena::Survey.find params[:survey_id]
      @version = @survey.versions.find params[:version_id]
    end

    def load_question_group
      @question_group = @version.question_groups.find params[:id]
    end

    def question_group_params
      params.require(:question_group).permit(:position, :title, :allow_to_go_back)
    end
  end
end

app/controllers/helena_administration/questions/bipolar_radio_matrices_controller.rb
module HelenaAdministration
  module Questions
    class BipolarRadioMatricesController < RadioMatricesController
    end
  end
end

app/controllers/helena_administration/questions/checkbox_groups_controller.rb
module HelenaAdministration
  module Questions
    class CheckboxGroupsController < QuestionsController
      private

      def add_ressources
        @question.sub_questions.build
      end

      def permited_params
        [:required, sub_questions_attributes: sub_questions_attributes]
      end
    end
  end
end

app/controllers/helena_administration/questions/checkbox_matrices_controller.rb
module HelenaAdministration
  module Questions
    class CheckboxMatricesController < QuestionsController
      include Helena::Concerns::Questions::MatrixQuestions
    end
  end
end

app/controllers/helena_administration/questions/checkbox_matrix_controller.rb
module HelenaAdministration
  module Questions
    class CheckboxMatrixController < QuestionsController
      include Helena::Concerns::Questions::MatrixQuestions
    end
  end
end

app/controllers/helena_administration/questions/long_texts_controller.rb
module HelenaAdministration
  module Questions
    class LongTextsController < QuestionsController
      private

      def permited_params
        %i[default_value required]
      end
    end
  end
end

app/controllers/helena_administration/questions/radio_groups_controller.rb
module HelenaAdministration
  module Questions
    class RadioGroupsController < QuestionsController
      private

      def add_ressources
        @question.labels.build
      end

      def permited_params
        [:required, labels_attributes: labels_attributes]
      end
    end
  end
end

app/controllers/helena_administration/questions/radio_matrices_controller.rb
module HelenaAdministration
  module Questions
    class RadioMatricesController < QuestionsController
      include Helena::Concerns::Questions::MatrixQuestions
    end
  end
end

app/controllers/helena_administration/questions/radio_matrix_controller.rb
module HelenaAdministration
  module Questions
    class RadioMatrixController < QuestionsController
      include Helena::Concerns::Questions::MatrixQuestions
    end
  end
end

app/controllers/helena_administration/questions/short_texts_controller.rb
module HelenaAdministration
  module Questions
    class ShortTextsController < QuestionsController
      private

      def permited_params
        %i[default_value required]
      end
    end
  end
end

app/controllers/helena_administration/questions/static_texts_controller.rb
module HelenaAdministration
  module Questions
    class StaticTextsController < QuestionsController
      private

      def permited_params
        %i[default_value required]
      end
    end
  end
end

app/controllers/helena_administration/questions_controller.rb
module HelenaAdministration
  class QuestionsController < ApplicationController
    respond_to :html

    before_action :load_question_group, :add_breadcrumbs
    before_action :load_question, only: %i[destroy edit update show]

    def show
      add_breadcrumb @question.code
    end

    def new
      @question = @question_group.questions.build
      add_breadcrumb t('.new')
    end

    def create
      @question = @question_group.questions.build question_params
      if @question.save
        flash[:success] = t 'shared.actions.created'
        respond_with @question, location: [@survey, @version, @question_group, @question]
      else
        flash[:danger] = t 'shared.actions.error'
        render 'new'
      end
    end

    def edit
      add_ressources
      add_breadcrumb @question.code
    end

    def update
      if @question.update_attributes(question_params)
        flash[:success] = t 'shared.actions.updated'
      else
        flash[:danger] = t 'shared.actions.error'
        add_breadcrumb @question.code_was
      end
      add_ressources
      respond_with @question, location: [@survey, @version, @question_group, @question]
    end

    def destroy
      flash[:success] = t 'shared.actions.deleted' if @question.destroy
      respond_with @question_group, location: [@survey, @version, @question_group]
    end

    private

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
      add_breadcrumb Helena::Survey.model_name.human(count: 2), surveys_path
      add_breadcrumb @survey.name, @survey
      add_breadcrumb t('helena_administration.versions.version', version: @version.version), [@survey, @version]
      add_breadcrumb @question_group.title, [@survey, @version, @question_group]
    end

    def load_question_group
      @survey = Helena::Survey.find params[:survey_id]
      @version = @survey.versions.find params[:version_id]
      @question_group = @version.question_groups.find params[:question_group_id]
    end

    def load_question
      @question = @question_group.questions.find params[:id]
    end

    def question_group_params
      params.require(:question).permit(:position, :title)
    end

    def labels_attributes
      %i[id position text value preselected _destroy]
    end

    def sub_questions_attributes
      %i[id position code text value preselected _destroy]
    end

    def question_params
      required_param.permit(permited_params + %i[position question_text code _type])
    end

    def permited_params
      []
    end

    def add_ressources; end

    def required_param
      param_name = self.class == QuestionsController ? :question : "questions_#{controller_name.singularize}"
      params.require(param_name)
    end
  end
end

app/controllers/helena_administration/sessions_controller.rb
require 'csv'
module HelenaAdministration
  class SessionsController < ApplicationController
    include ActionController::Live

    respond_to :html, :json, :csv

    before_action :load_survey, :add_breadcrumbs
    before_action :load_session, only: %i[edit update destroy]

    def index
      respond_to do |format|
        @sessions = @survey.sessions.desc(:created_at)
        format.json { render json: @sessions }
        format.csv do
          render_csv
        end
      end
    end

    def new
      @survey.sessions.create version: @survey.newest_version
      flash[:success] = t 'shared.actions.created'
      redirect_to survey_path(@survey)
    end

    def edit
      add_breadcrumb "#{@session.model_name.human}: #{@session.token_was}", @survey
    end

    def update
      if @session.update_attributes session_params
        flash[:success] = t 'shared.actions.updated'
      else
        flash.now[:danger] = t 'shared.actions.error'
        add_breadcrumb "#{@session.model_name.human}: #{@session.token_was}", @survey
      end
      respond_with @survey
    end

    def destroy
      flash[:success] = t 'shared.actions.deleted' if @session.destroy
      redirect_to survey_path(@survey)
    end

    private

    def render_csv
      response.headers['Content-Disposition'] = "attachment; filename=#{@survey.name}.csv"
      response.headers['Content-Type'] = 'text/csv'

      # Write csv header once ...
      response.stream.write CSV.generate_line(session_fields + ['version'] + question_codes)

      # .. and generate a line for each session.
      @sessions.each do |session|
        response.stream.write CSV.generate_line(session_values(session) + [session.version.version] + answer_values(session))
      end
    ensure
      response.stream.close
    end

    def session_values(session)
      session_fields.map { |field| session.attributes[field] }
    end

    def answer_values(session)
      answers = Hash[session.answers.map { |answer| [answer.code, answer.value] }]
      question_codes.map { |code| answers[code] }
    end

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
      add_breadcrumb Helena::Survey.model_name.human(count: 2), surveys_path
    end

    def load_survey
      @survey = Helena::Survey.find params['survey_id']
    end

    def load_session
      @session = @survey.sessions.find params[:id]
    end

    def session_params
      params.require(:session).permit :token, :view_token, :answers_as_yaml, :completed, :last_question_group_id
    end

    def question_codes
      @question_codes ||= unique_question_codes
    end

    # It could be possible that an answer code equals a session field. We add "answer_" in that case so that we get uniqe question codes for sure
    def unique_question_codes
      codes = @survey.versions.map(&:question_codes).flatten.uniq
      codes.map do |code|
        session_fields.include?(code) ? "answer_#{code}" : code
      end
    end

    def session_fields
      @session_fields ||= Helena::Session.fields.keys
    end
  end
end

app/controllers/helena_administration/surveys_controller.rb
module HelenaAdministration
  class SurveysController < ApplicationController
    respond_to :html

    before_action :add_breadcrumbs

    before_action :load_resources, only: %i[destroy edit update show]

    def index
      @surveys = Helena::Survey.asc(:position)
    end

    def new
      @survey = Helena::Survey.new
      add_breadcrumb t('shared.actions.new'), new_survey_path
    end

    def create
      add_breadcrumb t('shared.actions.new')

      @survey = Helena::Survey.new survey_params
      if @survey.save
        flash[:success] = t 'shared.actions.created'
      else
        flash.now[:danger] = t 'shared.actions.error'
      end
      respond_with @survey
    end

    def show
      add_breadcrumb @survey.name
      @sessions = Helena::Session.where(survey_id: @survey.id).desc(:updated_at).page(params[:page]).per(100)
    end

    def edit
      add_breadcrumb @survey.name
    end

    def update
      if @survey.update_attributes survey_params
        flash[:success] = t 'shared.actions.updated'
      else
        flash.now[:danger] = t 'shared.actions.error'
        add_breadcrumb @survey.name_was
      end
      respond_with @survey
    end

    def destroy
      flash.now[:success] = t 'shared.actions.deleted' if @survey.destroy
      respond_with @survey
    end

    private

    def load_resources
      @survey = Helena::Survey.find params[:id]
    end

    def add_breadcrumbs
      add_breadcrumb t('shared.navigation.dashboard'), dashboard_index_path
      add_breadcrumb Helena::Survey.model_name.human(count: 2), surveys_path
    end

    def survey_params
      params.require(:survey).permit(:name, :tag_list, :language)
    end
  end
end

app/helpers/helena_administration/application_helper.rb
module HelenaAdministration
  module ApplicationHelper
    def title(page_title)
      content_for :title, page_title.to_s
      page_title
    end

    # adds ... in between like if you have to long names in apple finder so you can i.e see the beginning and the suffix
    def truncate_between(str, after = 30)
      str = '' if str.nil?
      str.length > after ? "#{str[0..(after / 2) - 2]}...#{str[(str.length - ((after / 2) - 2))..str.length]}" : str
    end
  end
end

app/views/helena_administration/surveys/_form.html.slim
= simple_form_for(survey) do | f |
  = f.input :name
  = f.input :tag_list
  = f.input :language, collection: I18n.available_locales, include_blank: false
  = f.submit value: t('shared.actions.save'), class: 'btn btn-success'

app/views/helena_administration/surveys/edit.html.slim
= render 'form', survey: @survey

app/views/helena_administration/surveys/index.html.slim
table.table.table-striped
  thead
    tr
      th.position width='1%' #
      th.name = Helena::Survey.human_attribute_name(:name)
      th.lanugage  width='20%' = Helena::Survey.human_attribute_name(:language)
      th.created_at width='10%' = Helena::Survey.human_attribute_name(:created_at)
      th width='20%'
        = link_to new_survey_path, class: 'btn btn-dark pull-right', role: 'button' do
          i.fa.fa-plus-square
          = t('shared.actions.new')
        = link_to new_import_survey_path, class: 'btn btn-dark pull-right', role: 'button' do
          i.fa.fa-caret-square-o-up
          = t('.import')
  tbody
    - @surveys.each do |survey|
      tr id="#{dom_id(survey)}"
        td.position   = survey.position
        td.name       = link_to survey.name, survey_path(survey)
        td.language   = survey.language
        td.create_at  = distance_of_time_in_words_to_now(survey.created_at)
        td.actions
          .pull-right
            = link_to survey, class: 'btn btn-default', role: 'button' do
              i.fa.fa-angle-right
              = t('shared.actions.view')

            = link_to edit_survey_path(survey), class: 'btn btn-default', role: 'button' do
              i.fa.fa-edit
              = t('shared.actions.edit')

            = link_to survey, class: 'btn btn-danger', method: :delete, data: { confirm: t('shared.actions.ask_for_deletion') } do
              i.fa.fa-trash
              = t('shared.actions.delete')

app/views/helena_administration/surveys/new.html.slim
= render 'form', survey: @survey

app/views/helena_administration/surveys/show.html.slim
div id="#{dom_id(@survey)}"
  .row
    .col-md-10
      dl.row
        dt.col-sm-2 #
        dd.col-sm-10  = @survey.position

        dt.col-sm-2  = Helena::Survey.human_attribute_name :name
        dd.col-sm-10 = @survey.name

        dt.col-sm-2  = Helena::Survey.human_attribute_name :created_at
        dd.col-sm-10 = distance_of_time_in_words_to_now(@survey.created_at)

        dt.col-sm-2  = Helena::Survey.human_attribute_name :language
        dd.col-sm-10 = @survey.language
    .col-md-2
      .pull-right
        = link_to edit_survey_path(@survey), class: 'btn btn-dark', role: 'button' do
          i.fa.fa-edit
          = t('shared.actions.edit')

        = link_to survey_path(@survey), class: 'btn btn-danger', method: :delete, data: { confirm: t('shared.actions.ask_for_deletion') } do
          i.fa.fa-trash
          = t('shared.actions.delete')


  hr

  h3 = Helena::Version.model_name.human(count: 2)

  table.table.table-striped.versions
    thead
      tr
        th.version width='5%' = Helena::Version.human_attribute_name(:version)
        th.activity_state width='5%' = Helena::Version.human_attribute_name(:active)
        th.notes = Helena::Version.human_attribute_name(:notes)
        th.created_at width='10%' = Helena::Version.human_attribute_name(:created_at)
        th width='20%'
          = link_to new_survey_version_path(@survey), class: 'btn btn-dark pull-right', role: 'button' do
            i.fa.fa-plus-square
            = t('shared.actions.new')
    tbody
      - @survey.versions.desc(:version).each do |version|
        tr id="#{dom_id(version)}"
          td.version  = version.version
          td.activity_state
            - if version.active
              span.badge.badge-success = t 'shared.active'
            - else
              span.badge.badge-dark = t 'shared.inactive'
          td.notes      = version.notes
          td.create_at  = distance_of_time_in_words_to_now(version.created_at)
          td.actions
            .pull-right

              = link_to [@survey, version], class: 'btn btn-link', role: 'button' do
                i.fa.fa-angle-right
                = t('shared.actions.view')
              = link_to edit_survey_version_path(@survey, version), class: 'btn btn-link', role: 'button' do
                i.fa.fa-edit
                = t('shared.actions.edit')
              = link_to [@survey, version], class: "btn btn-danger #{'disabled' if version.active}", method: :delete, data: { confirm: t('shared.actions.ask_for_deletion') } do
                i.fa.fa-trash
                = t('shared.actions.delete')

  - if @survey.versions.any?
    hr
    h3.pull-left = Helena::Session.model_name.human(count: 2)
    = link_to survey_sessions_path(@survey, format: :csv), class: 'btn btn-dark pull-right', role: 'button' do
      i.fa.fa-download
      = t('.export_sessions_as_csv')

    = link_to survey_sessions_path(@survey, format: :json), class: 'btn btn-dark pull-right', role: 'button' do
      i.fa.fa-download
      = t('.export_sessions_as_json')

    table.table.table-striped.sessions
      thead
        tr
          th.completed width='5%' = Helena::Session.human_attribute_name(:completed)
          th.version width='5%' = Helena::Session.human_attribute_name(:version)
          th.token = Helena::Session.human_attribute_name(:token)
          th.view_token = Helena::Session.human_attribute_name(:view_token)
          th.updated_at width='10%' = Helena::Session.human_attribute_name(:updated_at)
          th.created_at width='10%' = Helena::Session.human_attribute_name(:created_at)
          th width='20%'
            = link_to new_survey_session_path(@survey), class: 'btn btn-dark pull-right', role: 'button' do
              i.fa.fa-plus-square
              = t('shared.actions.new')
      tfoot
        tr
          td colspan='7'
            .pull-right
              = paginate @sessions

      tbody
        - @sessions.each do |session|
          tr id="#{dom_id(session)}"
            td.completed
              - if session.completed
                span.badge.badge-success = t 'shared.completed'
              - else
                span.badge.badge-dark = t 'shared.not_completed'

            td.version = session.version.version
            td.token      = session.token
            td.view_token = session.view_token
            td.updated_at  = distance_of_time_in_words_to_now(session.updated_at)
            td.create_at  = distance_of_time_in_words_to_now(session.created_at)
            td.actions
              .pull-right
                = link_to helena.edit_session_path(session.token), class: 'btn btn-', role: 'button' do
                  i.fa.fa-play
                  = t('shared.actions.run')
                = link_to edit_survey_session_path(@survey, session), class: 'btn btn-default', role: 'button' do
                  i.fa.fa-edit
                  = t('shared.actions.edit')
                = link_to survey_session_path(@survey, session), class: 'btn btn-danger', method: :delete, data: { confirm: t('shared.actions.ask_for_deletion') } do
                  i.fa.fa-trash
                  = t('shared.actions.delete')